package Noyau;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ContactUE.java
//  @ Date : 13/11/2012
//  @ Author : 
//
//




public class ContactUE extends Personne {
	public Object bureau;
	private UE listeUE;
	
	public void setListeUE(UE listeUE) {
		this.listeUE = listeUE;
	}
	public UE getListeUE() {
		return listeUE;
	}
}
