package Noyau;

import java.io.Serializable;
import java.util.Vector;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ListeAuditeurs.java
//  @ Date : 13/11/2012
//  @ Author : 
//
//


public class ListeAuditeurs implements Serializable{
	public Vector<Auditeur> liste;
	
	public ListeAuditeurs(){
		liste = new Vector<Auditeur>();
	}
	
	public Boolean addAuditeur(Auditeur a) {
		if (! ifExistAuditeur(a)){
			liste.add(a);
			return true;
		}
		return false;
	}
	
	public Boolean ifExistAuditeur(Auditeur a) {
		for (int i =0; i<liste.size();i++){
			Auditeur ai = liste.get(i);
			
			if (ai.getNom().equalsIgnoreCase(a.getNom()) && 
					ai.getPrenom().equalsIgnoreCase(a.getPrenom())&&
							ai.getDateNaissance().equals(a.getDateNaissance())){
						return true;
					}						
		}
		return false;
	}
}
