package Noyau;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProfCnam.java
//  @ Date : 13/11/2012
//  @ Author : 
//
//




public class ProfCnam extends Prof {
	public String departement;
}
