package Noyau;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Prof.java
//  @ Date : 13/11/2012
//  @ Author : 
//
//




public class Prof extends Personne {
	public String nss;
	public UE listeUE;
}
