package Noyau;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UE.java
//  @ Date : 13/11/2012
//  @ Author : 
//
//




public class UE {
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public Short getEcts() {
		return ects;
	}
	public void setEcts(Short ects) {
		this.ects = ects;
	}
	public String getIntitule() {
		return intitule;
	}
	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}
	public String getLienInternet() {
		return lienInternet;
	}
	public void setLienInternet(String lienInternet) {
		this.lienInternet = lienInternet;
	}
	public String getNiveau() {
		return niveau;
	}
	public void setNiveau(String niveau) {
		this.niveau = niveau;
	}
	public ContactUE getContact() {
		return contact;
	}
	public void setContact(ContactUE contact) {
		this.contact = contact;
	}
	public Prof getProf() {
		return prof;
	}
	public void setProf(Prof prof) {
		this.prof = prof;
	}
	private String code;
	private Short ects;
	private String intitule;
	private String lienInternet;
	private String niveau;
	private ContactUE contact;
	public Prof prof;
}
