package Noyau;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vacataire.java
//  @ Date : 13/11/2012
//  @ Author : 
//
//




public class Vacataire extends Prof {
	public String employeur;
}
